sudo: required
dist: trusty
language: node_js

node_js:
  - 6

services:
  - postgresql

before_script:
  - psql -c 'create database doc_test;' -U postgres
  - NODE_ENV=test npm run migrate

script:
  - npm test

after_script: npm run coveralls
